name: Build Windows Executable

on:
  push:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pygame requests pyinstaller

    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --windowed game.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: game-windows
        path: dist/game.exe
